# __NAME__ — generated by the tamani golden path __GOLDEN_VERSION__.
# Correctness by default: a service scaffolded this way cannot ship
# without probes, limits, telemetry, network policy and monitoring.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: __NAME__
  namespace: tamani-dev
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: __NAME__
  namespace: tamani-dev
  labels: { app: __NAME__, golden-path: "__GOLDEN_VERSION__" }
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 0, maxUnavailable: 1 }
  selector:
    matchLabels: { app: __NAME__ }
  template:
    metadata:
      labels: { app: __NAME__ }
    spec:
      serviceAccountName: __NAME__
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile: { type: RuntimeDefault }
      containers:
        - name: app
          image: ghcr.io/maicymxtim/__NAME__:main
          imagePullPolicy: Always
          ports: [{ containerPort: __PORT__ }]
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: [ALL] }
          resources:
            requests: { cpu: 50m, memory: 96Mi }
            limits: { cpu: 250m, memory: 192Mi }
          startupProbe:
            httpGet: { path: /health/live, port: __PORT__ }
            failureThreshold: 30
            periodSeconds: 2
          readinessProbe:
            httpGet: { path: /health/ready, port: __PORT__ }
            periodSeconds: 10
          livenessProbe:
            httpGet: { path: /health/live, port: __PORT__ }
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: __NAME__
  namespace: tamani-dev
  labels: { app: __NAME__ }
spec:
  selector: { app: __NAME__ }
  ports: [{ port: 80, targetPort: __PORT__ }]
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: __NAME__
  namespace: tamani-dev
spec:
  podSelector:
    matchLabels: { app: __NAME__ }
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector: {}
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: monitoring
      ports:
        - port: __PORT__
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: __NAME__
  namespace: tamani-dev
spec:
  selector:
    matchLabels: { app: __NAME__ }
  endpoints:
    - targetPort: __PORT__
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: __NAME__-slo
  namespace: tamani-dev
spec:
  groups:
    - name: __NAME__.alerts
      rules:
        - alert: __ALERTNAME__HighErrorRate
          expr: |
            (sum(rate(http_requests_total{namespace="tamani-dev", handler!="/metrics", status=~"5..", job="__NAME__"}[5m])) or vector(0))
            / clamp_min(sum(rate(http_requests_total{namespace="tamani-dev", job="__NAME__"}[5m])), 1e-9) > 0.05
          for: 10m
          labels: { severity: warning, namespace: tamani-dev }
          annotations:
            summary: "__NAME__ error rate above 5%"
            runbook: runbooks/__NAME__.md
