apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: tamani-staging
resources:
  - ../../base
images:
  - name: tamani-api
    newTag: staging
  - name: tamani-gateway
    newTag: staging
  - name: tamani-worker
    newTag: staging
